---
# tasks file for roles/cis_windows

# Account Policies
- name: "CIS 2.3.1.2 | Disable Guest account"
  win_security_policy:
    section: System Access
    key: EnableGuestAccount
    value: 0
  tags: accounts

- name: "CIS 1.2.2 | Configure account lockout threshold (5 attempts)"
  win_security_policy:
    section: System Access
    key: LockoutBadCount
    value: 5
  tags: accounts

- name: "CIS 1.2.3 | Reset account lockout counter after 15 minutes"
  win_security_policy:
    section: System Access
    key: ResetLockoutCount
    value: 15
  tags: accounts

# Password Policies
- name: "CIS 1.1.1 | Enforce password history (24 passwords)"
  win_security_policy:
    section: System Access
    key: PasswordHistorySize
    value: 24
  tags: passwords

- name: "CIS 1.1.2 | Set maximum password age (60 days)"
  win_security_policy:
    section: System Access
    key: MaximumPasswordAge
    value: 60
  tags: passwords

# Login Security
- name: "CIS 1.1.2 | Hide last logged-in username"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: dontdisplaylastusername
    data: 1
    type: dword
  tags: login

- name: "CIS 2.3.7.3 | Set inactivity lock (900 seconds)"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: InactivityTimeoutSecs
    data: 900
    type: dword
  tags: login

# Firewall Rules
- name: "CIS 9.2.1 | Ensure private firewall is enabled"
  win_command: netsh advfirewall set privateprofile state on
  register: firewall_state
  changed_when: "'Ok.' not in firewall_state.stdout"
  tags: firewall

- name: "CIS 9.2.2 | Block inbound connections by default"
  win_command: netsh advfirewall set privateprofile firewallpolicy "blockinbound,allowoutbound"
  register: firewall_policy
  changed_when: "'Ok.' not in firewall_policy.stdout"
  tags: firewall

# Verification
- name: "Verify all policies applied"
  win_shell: |
    Write-Output "=== Account Policies ==="
    net accounts
    Write-Output "=== Registry Settings ==="
    reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v dontdisplaylastusername
    reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v InactivityTimeoutSecs
    Write-Output "=== Firewall Status ==="
    Get-NetFirewallProfile -Name Private | Select-Object Enabled,DefaultInboundAction
  register: verify
  changed_when: false

- name: "Display verification results"
  debug:
    var: verify.stdout_lines

# 🔻 Moved to the end to prevent loss of access 🔻
- name: "CIS 2.3.1.3 | Disable Administrator account (domain controllers only)"
  win_security_policy:
    section: System Access
    key: EnableAdminAccount
    value: 0
  ignore_errors: yes
  tags: accounts
