---
- name: Creating Jinja reports from MySQL database 
  hosts: db_servers
  become: yes
  tasks:
    
    - name: Query Avenger data from MySQL
      community.mysql.mysql_query:
        login_db: avengers_db
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        query: "SELECT * FROM characters;"
      register: avenger_data

    - name: Generate system report using Jinja2 template
      template:
        src: ../templates/avenger_report.md.j2
        dest: /tmp/avengers_report.md

    - name: fetch the generated template to control node
      fetch:
        src: /tmp/avengers_report.md
        dest: ~/repo/srt205-labs/lab10/reports/avengers_report.md
        flat: yes

