---
- name: Disable IPv6 via sysctl
  become: yes
  blockinfile:
    path: /etc/sysctl.d/99-disable-ipv6.conf
    block: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
    create: yes
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl changes
  become: yes
  command: sysctl --system
