---
- name: Disable root login over SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    create: yes
  notify: restart ssh

- include_tasks: password_expiry.yml
- include_tasks: ptrace_restriction.yml
- include_tasks: auto_updates.yml
- include_tasks: ufw.yml
- include_tasks: cron_restriction.yml
- include_tasks: password_complexity.yml
- include_tasks: disable_ipv6.yml
- include_tasks: harden_tmp.yml
- include_tasks: auditd.yml
