---
- name: Enforce password complexity in pwquality.conf
  blockinfile:
    path: /etc/security/pwquality.conf
    block: |
      minlen = 12
      dcredit = -1
      ucredit = -1
      ocredit = -1
      lcredit = -1
    create: yes
    owner: root
    group: root
    mode: '0644'
