---
- name: Playbook with Blocks
  hosts: managed_node01
  become: yes
  tasks:

    - name: Block of tasks
      block:
        - name: Uninstall nginx
          apt:
            name: nginx
            state: absent

        - name: Install apache2
          apt:
            name: apache2
            state: present

        - name: Replace content of /var/www/html/
          copy:
            dest: /var/www/html/index.html
            content: |
              <html>
                <head>
                  <title>Welcome to Apache2</title>
                </head>
                <body>
                  <h1>Apache2 is Running Successfully!</h1>
                </body>
              </html>

        - name: Simulate failure
          command: /bin/false

      rescue:  #used for when any task in the block fails
        - name: Display debug message
          debug:
            msg: "An error occurred, executing rescue tasks!"

        - name: Ensure Apache is started and enabled
          service:
            name: apache2
            state: started
            enabled: yes

