---
- name: Secrets Test Playbook
  hosts: db_servers
  become: true
  
  vars_files:
    - secrets/vault_vars.yml

  tasks:

    - name: Show API Key and Access Pass (Debug)
      debug:
        msg:
          - "API Key: {{ api_key }}"  
          - "Access Password: {{ access_pass }}"  

    - name: Create secrets file from template
      template:
        src: secret_keys.config.j2
        dest: /tmp/secret_keys.config
