---
- name: Challenge Playbook
  hosts: managed_node01
  become: yes

  tasks:
    - name: Stop and disable NGINX service
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy index.html to Apache web directory
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Backup /var/www/ansible-lab directory
      archive:
        path: /var/www/ansible-lab
        dest: /var/backups/ansible-lab-backup.tar.gz
        format: gz

